### ISSUE TITLE
Bug : silent does not work in new version

### ISSUE THREAD

**Issue by D3miS3raph** [PokeAlert/PokeAlert#162]
Lg v10
Silent in settings still plays my default phone sound.  If i pick a sound they work. Silent goes back to default sound not silent.

Then if you try to pick a pokemon.  Select its sound and select silent it tells me that sound cant be found.  So again no way to make notifications silent.  Always get sound.

**Comment by PokeAlert** [comment]
Can I have a screen shot of the notification dialog? (I dont have any silent thing on mine)

**Comment by D3miS3raph** [comment]
![screenshot_2016-09-22-07-43-31](https://cloud.githubusercontent.com/assets/22326709/18747029/ede21b5e-8098-11e6-97f9-156148c4d0f6.png)

![screenshot_2016-09-22-07-43-37](https://cloud.githubusercontent.com/assets/22326709/18747035/fba219d8-8098-11e6-99a2-cbdbbe86dbde.png)

Thats from filter section and this is from notification

![screenshot_2016-09-22-07-50-33](https://cloud.githubusercontent.com/assets/22326709/18747096/498d569e-8099-11e6-96ce-7724c7977adc.png)

**Comment by D3miS3raph** [comment]
So just need it to be if silent play no sound.  Vibrate is fine and has its own toggle. But every alert playing a sound definitely not good.

**Comment by PokeAlert** [comment]
Yep, just fixed in 2.3.15-2 will be released shortly

**Comment by D3miS3raph** [comment]
Awesome greatly appreciated! Looking forward to it

**Comment by D3miS3raph** [comment]
Sadly still broken.  Still plays sound even when silwnt selected for pokwmon and in notification settings

**Comment by D3miS3raph** [comment]
Additional issue.  Even with vibrate toggled off it still vibrates when use default sound is toggled off...
